name: Terraform

on:
  push:
    paths-ignore:
      - "**.tfstate"
      - "**.tfstate.encrypted"
    branches:
      - main


jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Vérifiez le code source du repo
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download Artifact
      uses: badgerhobbs/terraform-state@v2
      with:
          operation: download
          location: artifact
          github_token: ${{ secrets.gh_access_token }}
      continue-on-error: true

    # Installe Terraform
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2

    # Fmt
    - name: Terraform fmt
      run: terraform fmt -check

    # Init Terraform
    - name: Terraform Init
      run: terraform init

    # Plan Terraform
    - name: Terraform Plan
      run: terraform plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    # Apply Terraform avec confirmation automatique (-auto-approve)
    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    - name: Upload Artifact
      uses: badgerhobbs/terraform-state@v2
      with:
          operation: upload
          location: artifact
          github_token: ${{ secrets.gh_access_token }}

